max_E: 6.0
max_p: 0.1
OMP_NUM_THREADS: 20
MKL_NUM_THREADS: 20
dummy_distance: 2.1
use_scratch: False
remove_scratch: True
reduce_output: True
add_Pd_Cl2: False
add_Pd_Cl2_PH3: False
add_Ni_CO_3: True
